### PR TITLE
Add diagnostic for #258, a struct mutating itself.

### PR DESCRIPTION
**Pull request by nemec**
I ended up adding a new diagnostic category for "structs", given that there are a few more open issues regarding structs, but I'm not sure what your policy is regarding category assignment.

### CODE REVIEW

**Comment by Hosch250** [comment]
Looks nice.  Generally we would use the "General" category for this, but I've been thinking lately that we should add a few more categories.  If you wish to chat about this project, we have a chatroom setup at Code Review.SE: http://chat.stackexchange.com/rooms/26639/vsdiagnostics

**Comment by Vannevelj** [comment]
Looks good! The added category is fine -- maybe we should look into creating more categories anyway.

Would you mind adding a few more tests to account for different execution paths? I'm thinking like for example assiging `new X(5)` to a variable instead of `this`. This will prevent us from creating problems in the future should that diagnostic ever need refactoring.

**Comment by nemec** [comment]
@Hosch250 bookmarked! I'll hang around.

@Vannevelj you're thinking of additional negative tests? Sure, I'll add a few of those and get back to you.

**Comment by nemec** [comment]
Added more tests to the commit.

**Comment by Vannevelj** [comment]
Great additions! This looks good and will be included in the next release. I appreciate the effort you've undertaken, @nemec

**Pull request merged**
